# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.22.0'
    
    - name: install all  
      working-directory: ./ember-app
      run: |
        npm install -g ember-cli@3.1.4
        npm install
        ember build 
    
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: ./dist
